# Generated by Django 5.1.7 on 2025-05-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferenciasusuario',
            old_name='data_criacao',
            new_name='criado_em',
        ),
    ]
