# Generated by Django 5.1.7 on 2025-05-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_rename_data_criacao_preferenciasusuario_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciasusuario',
            name='horas_por_semana',
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='horas',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferenciasusuario',
            name='recomendacoes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
